### ISSUE TITLE
The develop branch broken?

### ISSUE THREAD

**Issue by Atlantic777** [mps-youtube/mps-youtube#362]
How to reproduce:

```
git clone https://github.com/mps-youtube/mps-youtube
cd mps-youtube
git checkout develop
./mpsyt
# search for a song (fine)
# try to play it -> crash
git checkout master
./mpsyt
# search for the same song
# try to play it -> ok
```

Here is stack trace I'm getting:

```
Traceback (most recent call last):
  File "./mpsyt", line 3, in <module>
    mps_youtube.main.main()
  File "/tmp/mps-youtube/mps_youtube/main.py", line 3797, in main
    if matchfunction(k, v, userinput):
  File "/tmp/mps-youtube/mps_youtube/main.py", line 3694, in matchfunction
    func(*matches)
  File "/tmp/mps-youtube/mps_youtube/main.py", line 2527, in play
    play_range(songlist, shuffle, repeat, override)
  File "/tmp/mps-youtube/mps_youtube/main.py", line 2620, in play_range
    returncode = playsong(song, override=override)
  File "/tmp/mps-youtube/mps_youtube/main.py", line 1203, in playsong
    streams.get(song, force=failcount, callback=writestatus)
  File "/tmp/mps-youtube/mps_youtube/streams.py", line 70, in get
    rawbitrate=s.rawbitrate,
  File "/usr/local/lib/python3.4/dist-packages/pafy/pafy.py", line 812, in rawbitrate
    return self._rawbitrate
AttributeError: 'Stream' object has no attribute '_rawbitrate'
```

**Comment by ids1024** [comment]
What version of pafy do you have?

**Comment by ids1024** [comment]
Fixed in mps-youtube/pafy@88fda70563057ba5a460641febb08dd2ff71c036 on the 0.3.x branch of pafy, so the next release on that branch will be fixed. It already worked on pafy 0.4.0/0.4.1.

I may add some code in mpsyt so it will work on the older pafy versions as well, though this is ultimately a bug in pafy.

**Comment by ids1024** [comment]
I added such a workaround in commit 275a5383ab8f481396bf9cfe7d66646bc9533838.

**Comment by Atlantic777** [comment]
Yep, I was using old pafy, and your commit fixes it for 0.3x branch. Thanks!
